### ISSUE TITLE
4th sprint

### ISSUE THREAD

**Issue by 0x41gawor** [0x41gawor/lupus#10]
- [x] Remove Learn element #13 
	- [x] Remove Learn type, its controller and docs.
- [x] Field nesting in Data #11 
	- [x] Add new Action of type "print" that prints the data
	- [x] Temporarily change the Data sent by managed-system/mc-server to contain nesting e.g. {"ram": {"ram2": {"in_use": 14, "license: 20"}}, "cpu": {"in_use": 8, "license: 8"}}, and adjust master LupN to read inputKey of `"ram.ram2"` instead of "ram". cpu leave as it is to test both cases nested and non nested.
	- [x] Code the nesting with `.` in Data fields. Handle errors e.g. when nested field is actually not `map[string]interface{}`. 
- [x] LupN #12 
	- [x] Create docs document of LupN. First make overview of workflows. Then state requirements for LupN. What kind of workflow "features" it should allow. Discuss flow control statements from https://www.learncpp.com/cpp-tutorial/control-flow-introduction/
	- [x] Prepare some managed-system that will require Conditional Statements and Halts in its loop workflow. Also remember that later you will replace some http call with internal go func.
	- [x] In docs, design the notation for Conditional Statements and Halts.
	- [x] Implement, run and test.
- [x] GoFunc as Action Destination #14
	- [x] Create new type of Destination called `gofunc`.
	- [x] Research how it can be implemented. Does GO allow dynamic func name resolution? Will user only implement func with certain name and use this name in LupN or is he forced to modify Lupus code (more precisely Decide controller)
	- [x] Implement

Progress will be trakced here (as for mind health, single place where you can see all achievements is really good).
But Issues regarding one task will state as place for discussion about them.
